namespace ChemiDemo.DataContext.Schema
{
    using FluentMigrator;

    [Migration(201711281609)]
    public class Seed
        : Migration
    {
        public override void Down()
        {
            Delete.FromTable("tblProduct").AllRows();
        }

        public override void Up()
        {
            Insert.IntoTable("tblProduct")
                .Row(new { ProductName = "Absol", SupplierName = "Yxhult/Svesten AB", Uri = "http://www.yxhult.se/_pdf/absol/Absol_sakerhetsdatablad_ver_12_se.pdf" })
                .Row(new { ProductName = "Addinol Semi Synth Mv 1047", SupplierName = "Addinol Lube Oil GmbH", Uri = "http://www.addinol.de/oilfinder/show_msds.php?id=38163" })
                .Row(new { ProductName = "Addinol Super Ligth Mv 0546", SupplierName = "Addinol Lube Oil GmbH", Uri = "http://www.addinol.de/oilfinder/show_msds.php?id=43475" })
                .Row(new { ProductName = "Anderol 6150", SupplierName = "Anderol BV", Uri = "http://www.anderol-europe.com/images/anderol/msds/SV__ANDEROL%206150_6150_SDS_20111020__ANDEROL_.PDF" })
                .Row(new { ProductName = "Anderol FGH 32", SupplierName = "Anderol BV", Uri = "http://www.anderol-europe.com/images/anderol/msds/SV__ANDEROL%20FGH%2032_FGH%2032_SDS_20111129__ANDEROL_.PDF" })
                .Row(new { ProductName = "Anti-static fluid", SupplierName = "Xerox", Uri = "http://www.xerox.com/download/ehs/msds/4-0071.da.pdf" })
                .Row(new { ProductName = "Bell®", SupplierName = "Hedegaard A/S", Uri = "http://datablade.dlaagro.com/Bell_-_150911.pdf" })
                .Row(new { ProductName = "Beskyttelsescreme", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/120.pdf" })
                .Row(new { ProductName = "Biopower", SupplierName = "Hedegaard A/S", Uri = "http://www.middeldatabasen.dk/pdf/msds/Biopower_MSDS_20080901.pdf" })
                .Row(new { ProductName = "Bison Plastlim", SupplierName = "Nilfisk-Frithiof", Uri = "http://www.nilfisk-frithiof.dk/files/pdf/produktdatablad_pvc_lim.pdf" })
                .Row(new { ProductName = "Blasocut® Bc 35 Kombi", SupplierName = "Duroc Machine Tools A/S", Uri = "http://www.duroc.com/media/782154/sikkerhedsdatablad_-_blasocut_bc_35_kombi.pdf" })
                .Row(new { ProductName = "Bore-Skære-Olie (Sprayprodukt)", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/570.pdf" })
                .Row(new { ProductName = "Briotril 400 EC", SupplierName = "Hedegaard A/S", Uri = "http://www.makhteshim-agan.nl/beheer/plaat/15207031DK%20Briotril%20400EC%20%28DK%29.pdf" })
                .Row(new { ProductName = "Buffer 4.0", SupplierName = "Reagecon Diagnostics Limited", Uri = "http://www.certs.reagecon.com/msds/da_/JR_2822_15da_.pdf" })
                .Row(new { ProductName = "Buffer Rlt", SupplierName = "Qiagen Danmark, Filial Af Qiagen AB, Sverige", Uri = "http://www.qiagen.com/data/Support/MSDS/DK/Buffer_RLT_DK7.pdf" })
                .Row(new { ProductName = "Buffer RLT plus", SupplierName = "Qiagen Danmark, Filial Af Qiagen AB, Sverige", Uri = "http://www.qiagen.com/data/Support/MSDS/DK/Buffer_RLT_plus_DK5.pdf" })
                .Row(new { ProductName = "Buffer RW1", SupplierName = "Qiagen Danmark, Filial Af Qiagen AB, Sverige", Uri = "http://www.qiagen.com/data/Support/MSDS/DK/Buffer_RW1_DK7.pdf" })
                .Row(new { ProductName = "C5-A Copper Anti-Seize Stick", SupplierName = "Henkel Norden AB", Uri = "http://mymsds.henkel.com/mymsds/0006.466863.7200.sv.MSDS_UT_SE.SE.pdf" })
                .Row(new { ProductName = "Cæsium format opløsning", SupplierName = "Cabot Specialty Fluids", Uri = "http://www.formatebrines.com/Portals/2/Datasheets/CESFORMSOL-EUR-DA.pdf" })
                .Row(new { ProductName = "Callisto", SupplierName = "Hedegaard A/S", Uri = "http://www.syngenta.com/country/dk/da/plantebeskyttelse/produkter/ukrudtsmidler/Documents/Callisto-SDS.pdf" })
                .Row(new { ProductName = "Citronsyramonohydrat Pulver Ph.eur.", SupplierName = "VWR International AB", Uri = "https://se.vwr.com/app/asset?type=hi_res&id=7670430&name=sds_VWRC85514&filename=7670430.pdf" })
                .Row(new { ProductName = "Cool Dow", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/479.pdf", UserName = "87456709", Password = "chemicontrol" })
                .Row(new { ProductName = "Creatine Monohydrate Biochemica", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A3132_da_DK.pdf" })
                .Row(new { ProductName = "Daglig Rengøring", SupplierName = "Stonetreatment ApS", Uri = "http://www.stonetreatment.dk/media/784/lba-daglig_rengoring.pdf" })
                .Row(new { ProductName = "Daglig Rengøring", SupplierName = "Stonetreatment ApS", Uri = "http://www.stonetreatment.dk/media/784/lba-daglig_rengoring.pdf" })
                .Row(new { ProductName = "Delaval Mastitis Test Cmt", SupplierName = "DELAVAL A/S", Uri = "http://www.delaval.dk/ImageVaultFiles/id_6409/cf_5/DeLavalMastitisTestCMT.pdf" })
                .Row(new { ProductName = "Diammoniumperoxodisulfat", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A0834_da_DK.pdf" })
                .Row(new { ProductName = "DynoRex", SupplierName = "Orica Denmark A/S", Uri = "http://www.oricaminingservices.com/download/file_id_11666/" })
                .Row(new { ProductName = "Eclipse Hard Floor Sealer", SupplierName = "PETER LUDVIGSEN A/S", Uri = "http://www.peter-ludvigsen.dk/pdf/pioneer/Hard_Floor_Sealer.pdf" })
                .Row(new { ProductName = "Eclipse Neutral Cleaner", SupplierName = "PETER LUDVIGSEN A/S", Uri = "http://www.peter-ludvigsen.dk/pdf/pioneer/Neutral_Cleaner.pdf" })
                .Row(new { ProductName = "Edta Calibration Sample", SupplierName = "Leco Corporation  Svenska AB", Uri = "http://arkiv.lecoswe.se/pdf/MSDS/DK/502-092(DK).pdf", UserName = "lecocust", Password = "pdffiles" })
                .Row(new { ProductName = "Eletronic-Spray 200ml Art.: 2832", SupplierName = "Auto-G Holstebro A/S", Uri = "http://www.chemical-check.de/clientversion/pdf1/566/2832_0008_03-11-2009_DA.pdf" })
                .Row(new { ProductName = "Ferodo Dot 4 Esp", SupplierName = "Aktieselskabet Carl Christense", Uri = "http://www.msystem.dk/consumer/sikkerhedsdatablad.aspx?kid=6801" })
                .Row(new { ProductName = "Flamol B", SupplierName = "A B PLANTESERVICE", Uri = "http://www.flamol.dk/Flamol%20B.pdf" })
                .Row(new { ProductName = "Flamol K", SupplierName = "A B PLANTESERVICE", Uri = "http://www.flamol.dk/Flamol%20K.pdf" })
                .Row(new { ProductName = "Foodmax Bore- & Monteringspasta", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/H590.pdf" })
                .Row(new { ProductName = "Furnace Reagent", SupplierName = "Leco Corporation  Svenska AB", Uri = "http://arkiv.lecoswe.se/pdf/MSDS/DK/501-609-HAZ(DK).pdf", UserName = "lecocust", Password = "pdffiles" })
                .Row(new { ProductName = "Glyphomax* Herbicide (naf-595)", SupplierName = "Hedegaard A/S", Uri = "http://www.middeldatabasen.dk/pdf/MSDS/Glyphomax_MSDS_20101029.pdf" })
                .Row(new { ProductName = "Graco Pump Armor", SupplierName = "GRACO N.V.", Uri = "http://gww.graco.com/docs/MSDS/Danish/MSD029A.pdf" })
                .Row(new { ProductName = "Grease Spray", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/H588.pdf" })
                .Row(new { ProductName = "Grundrens", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/360.pdf", UserName = "87456709", Password = "chemicontrol" })
                .Row(new { ProductName = "Hakupur 19-283", SupplierName = "Jens Linde A/S", Uri = "http://jenslinde.dk/userfiles/image/PDF/HAKUPUR_19-283.pdf" })
                .Row(new { ProductName = "Hydrochloric Acid 1.128 % (w/v) P. A.", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A2768_da_DK.pdf" })
                .Row(new { ProductName = "Hylomar Universal Blue", SupplierName = "Ermax A/S", Uri = "http://www.ermax.dk/Files/Filer/nyErmax/Servicevejledninger/hylomar_universal_blue.pdf" })
                .Row(new { ProductName = "Hylomar Universal Blue", SupplierName = "Ermax A/S", Uri = "http://www.ermax.dk/Files/Filer/nyErmax/Servicevejledninger/hylomar_universal_blue.pdf" })
                .Row(new { ProductName = "Kalkfjerner Super", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/208.pdf", UserName = "87456709", Password = "chemicontrol" })
                .Row(new { ProductName = "Kerb 500 Sc Herbicide", SupplierName = "Hedegaard A/S", Uri = "http://planteapp.dlbr.dk/Middeldatabasen/pdf/msds/Kerb%20500SC_MSDS_20060607.pdf" })
                .Row(new { ProductName = "Kt Flyvrustfjerner", SupplierName = "KlarTek Danmark ApS", Uri = "http://www.klartek.dk/datablade/1319020820__-_KT-Flugrostentferner_PKW_(DK.pdf" })
                .Row(new { ProductName = "Kt Lawine Blau Vollwaschpulver", SupplierName = "KlarTek Danmark ApS", Uri = "http://www.klartek.dk/datablade/1320329081__-_KT_Lawine_Blau_Vollwaschpulver_(DK.pdf" })
                .Row(new { ProductName = "Kvartssand", SupplierName = "Dansk Kvarts Industri A/S", Uri = "http://www.kvarts.dk/files/manager/kvartssand.pdf?viewer=true" })
                .Row(new { ProductName = "LM 40 Multi-Funktions-Spray 400ml Art.:2816", SupplierName = "Auto-G Holstebro A/S", Uri = "http://www.chemical-check.de/clientversion/pdf1/566/2816_0009_24-02-2010_DA.pdf" })
                .Row(new { ProductName = "Loctite 561", SupplierName = "Henkel Norden AB", Uri = "http://mymsds.henkel.com/mymsds/0006.540917.7200.sv.MSDS_UT_SE.pdf" })
                .Row(new { ProductName = "Loctite 668", SupplierName = "Henkel Norden AB", Uri = "http://mymsds.henkel.com/mymsds/0006.705002.7200.sv.MSDS_UT_SE.SE.pdf" })
                .Row(new { ProductName = "Maintenancespray White 250ml Art.:2872", SupplierName = "Auto-G Holstebro A/S", Uri = "http://www.chemical-check.de/clientversion/pdf1/566/2872_0011_06-07-2009_DA.pdf" })
                .Row(new { ProductName = "Mangansulfat Monohydrat", SupplierName = "Hedegaard A/S", Uri = "http://planteapp.dlbr.dk/middeldatabasen/pdf/MSDS/Mangansulfat_32_MSDS_20091208.pdf" })
                .Row(new { ProductName = "Montage-Lim", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/432.pdf", UserName = "87456709", Password = "chemicontrol" })
                .Row(new { ProductName = "Myremiddel Til Udvanding", SupplierName = "TANACO DANMARK A/S ", Uri = "http://www.tanaco.dk/cms/modules/ContentExpress/img_repository/Myremiddel%20til%20udvanding.pdf" })
                .Row(new { ProductName = "Nicanor 20 Sg", SupplierName = "Hedegaard A/S", Uri = "http://www.makhteshim-agan.nl/beheer/plaat/Nicanor%2020SG%20%28H%29%20%28DK%29.pdf" })
                .Row(new { ProductName = "Nitric Acid - Standard Volumetric Acid (0.5 M)", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A2690_da_DK.pdf" })
                .Row(new { ProductName = "Nitric Acid 20 % Technical Grade", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A0940_da_DK.pdf" })
                .Row(new { ProductName = "Nobelcord, F-cord 10, E-cord", SupplierName = "Orica Denmark A/S", Uri = "http://www.oricaminingservices.com/download/file_id_11755/" })
                .Row(new { ProductName = "Nobelit EP", SupplierName = "Orica Denmark A/S", Uri = "http://www.oricaminingservices.com/download/file_id_11685/" })
                .Row(new { ProductName = "Notrac Museblok", SupplierName = "Mortalin Produktion ApS", Uri = "http://www.mortalin.dk/files/pdf/Notrac_Museblok_28_g_vers_2_7-3-20011.pdf" })
                .Row(new { ProductName = "Notrac Museblok 28 g", SupplierName = "Mortalin Produktion ApS", Uri = "http://www.mortalin.dk/files/pdf/Notrac_Rotteblok_28_g_-_bromadiolon_-_MSDS_-vers_2_7-3-20011.pdf" })
                .Row(new { ProductName = "Notrac Rotteblok 28 g", SupplierName = "Mortalin Produktion ApS", Uri = "http://www.mortalin.dk/files/pdf/Notrac_Rotteblok_28_g_-_bromadiolon_-_MSDS_-vers_2_7-3-20011.pdf" })
                .Row(new { ProductName = "Opticid", SupplierName = "DELAVAL A/S", Uri = "http://www.delaval.dk/ImageVaultFiles/id_13546/cf_5/OptiCid_dk.PDF" })
                .Row(new { ProductName = "Pirimor G", SupplierName = "Hedegaard A/S", Uri = "http://www.syngenta.com/country/dk/SiteCollectionDocuments/Pirimor-SDS-DK.pdf" })
                .Row(new { ProductName = "Potassium Dichromate - Standard Volumetric Solution (0.033 M) For Cod-determinatio", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A3319_da_DK.pdf" })
                .Row(new { ProductName = "Potassium Ferrocyanide Trihydrate P. A.", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A1867_da_DK.pdf" })
                .Row(new { ProductName = "Pyrethrum Mod Fluer", SupplierName = "TANACO DANMARK A/S ", Uri = "http://www.tanaco.dk/cms/modules/ContentExpress/img_repository/Pyrethrum.pdf" })
                .Row(new { ProductName = "R10 Lugtfjerner", SupplierName = "Trade Nordic", Uri = "http://shop.mediqdanmark.dk/web_filer/72/72-90-R10%20sikkerhedsdatablad%20DK.pdf" })
                .Row(new { ProductName = "Rebound Cleaner/Enhancer", SupplierName = "PETER LUDVIGSEN A/S", Uri = "http://www.peter-ludvigsen.dk/pdf/pioneer/Rebound_Cleaner.pdf" })
                .Row(new { ProductName = "RTU Xtra, bag in ca", SupplierName = "TANACO DANMARK A/S ", Uri = "http://www.tanaco.dk/cms/modules/ContentExpress/img_repository/RTU%20Xtra,%20bic.pdf" })
                .Row(new { ProductName = "Schnellreiniger 5l", SupplierName = "Auto-G Holstebro A/S", Uri = "http://www.autog.dk/Admin/Public/DWSDownload.aspx?File=Files%2fFiler%2fDatablade%2f2824.pdf" })
                .Row(new { ProductName = "Silicone Spray", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/H580.pdf" })
                .Row(new { ProductName = "Siliconspray 300ml Art.: 2899", SupplierName = "Auto-G Holstebro A/S", Uri = "http://www.chemical-check.de/clientversion/pdf1/566/2899_0009_29-06-2009_DA.pdf" })
                .Row(new { ProductName = "Silvernitrat 0,1 Mol/l (0,1 N) Vattenlösning Avs Titrinorm® Volumetrisk  Lösning", SupplierName = "VWR International AB", Uri = "https://se.vwr.com/app/asset?type=hi_res&id=7901949&name=sds_VWRC30472&filename=7901949.pdf" })
                .Row(new { ProductName = "Sol Lotion Faktor 30", SupplierName = "Care Repair", Uri = "http://www.care-repair.dk/pdf_out/132.pdf", UserName = "87456709", Password = "chemicontrol" })
                .Row(new { ProductName = "Stald Chok D", SupplierName = "TANACO DANMARK A/S ", Uri = "http://www.tanaco.dk/cms/modules/ContentExpress/img_repository/Stald%20Chok.pdf" })
                .Row(new { ProductName = "Stonetreatment Daglig Rengøring", SupplierName = "Stonetreatment ApS", Uri = "http://www.stonetreatment.dk/media/784/lba-daglig_rengoring.pdf" })
                .Row(new { ProductName = "Stonetreatment Grundrengøring", SupplierName = "Stonetreatment ApS", Uri = "http://www.stonetreatment.dk/media/719/lba-grundrengoring.pdf" })
                .Row(new { ProductName = "Stonetreatment Grundrengøring", SupplierName = "Stonetreatment ApS", Uri = "http://www.stonetreatment.dk/media/719/lba-grundrengoring.pdf" })
                .Row(new { ProductName = "Super", SupplierName = "DELAVAL A/S", Uri = "http://www.delaval.dk/ImageVaultFiles/id_13553/cf_5/Super.PDF" })
                .Row(new { ProductName = "Svovlsyre 50 %", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A2102_da_DK.pdf" })
                .Row(new { ProductName = "SWEPCO 101 Moly Grease", SupplierName = "Lubco Danmark", Uri = "http://swepcousa.com/lubesite/lubemsds/101%20Danish.pdf", UserName = "MSDSlube", Password = "$Rep1933" })
                .Row(new { ProductName = "Swepco 121 Tri-Plex Universal Grease", SupplierName = "Lubco Danmark", Uri = "http://swepcousa.com/lubesite/lubemsds/121%20Danish.pdf", UserName = "MSDSlube", Password = "$Rep1933" })
                .Row(new { ProductName = "Swepco 815 Food Machinery Grease (Aerosol)", SupplierName = "Lubco Danmark", Uri = "http://swepcousa.com/lubesite/lubemsds/815%20Danish%20UN1950.pdf", UserName = "MSDSlube", Password = "$Rep1933" })
                .Row(new { ProductName = "Tacky Lube Spray 400ml Art.:2842", SupplierName = "Auto-G Holstebro A/S", Uri = "http://www.chemical-check.de/clientversion/pdf1/566/2842_0010_07-09-2010_DA.pdf" })
                .Row(new { ProductName = "Toner (sort, cyan, Magenta, gul)", SupplierName = "Xerox", Uri = "http://www.xerox.com/download/ehs/msds/3-1176.da.pdf//download/ehs/msds/3-1176.da.pdf" })
                .Row(new { ProductName = "Tork Premium Flydende Sæbe - Mild", SupplierName = "SCA Hygiene Products A/S", Uri = "http://img.sca-tork.com/medias/sys_master/8833033535518.pdf?mime=application%2Fpdf&realname=420501%2C+420502%2C+400505+Mild.pdf" })
                .Row(new { ProductName = "Tp 100 Forte", SupplierName = "KlarTek Danmark ApS", Uri = "http://www.klartek.dk/datablade/1319017701__-_TP_100_Spezial_(DK.pdf" })
                .Row(new { ProductName = "TP 400 Chassis S", SupplierName = "KlarTek Danmark ApS", Uri = "http://www.klartek.dk/datablade/1319017701__-_TP_400_Chassis_S_(DK.pdf" })
                .Row(new { ProductName = "TRAFFIC AMPERE P Farve blå og grå", SupplierName = "Backner ApS", Uri = "http://www.backner.dk/contents/da/DK_Traffic_blaa_graa.pdf" })
                .Row(new { ProductName = "TRAFFIC AMPERE P Farve gul og hvid", SupplierName = "Backner ApS", Uri = "http://www.backner.dk/contents/da/DK_Traffic_gul_og_hvid.pdf" })
                .Row(new { ProductName = "Traffic Ampere P Farve Rød Og Grøn / Traffic Ampere P Extra Hvid", SupplierName = "Backner ApS", Uri = "http://www.backner.dk/contents/da/DK_Traffic_rod_gron_Traffic_Extra_hvid.pdf" })
                .Row(new { ProductName = "Tris-(hydroxymethyl) Aminomethan (tris) Analar Normapur® Analyse Reagens", SupplierName = "AppliChem GmbH", Uri = "https://dk.vwr.com/app/asset?type=hi_res&id=7667805&name=sds_BDHA10315&filename=sds_BDHA10315.pdf" })
                .Row(new { ProductName = "Tsl-væske Til Halspakning", SupplierName = "GRACO N.V.", Uri = "http://www.graco.com/content/dam/graco/tech_documents/msds/da/MSD122W.pdf" })
                .Row(new { ProductName = "Vask & Voks", SupplierName = "KlarTek Danmark ApS", Uri = "http://www.klartek.dk/datablade/1319017701__-_Wash_&_Wax_(DK.pdf" })
                .Row(new { ProductName = "Ventil Sauber 150ml Art.: 2809", SupplierName = "Auto-G Holstebro A/S", Uri = "http://www.chemical-check.de/clientversion/pdf1/566/2809_0012_27-04-2010_DA.pdf" })
                .Row(new { ProductName = "Zinc Acetate Dihydrate P. A.", SupplierName = "AppliChem GmbH", Uri = "http://www.applichem.com/fileadmin/datenblaetter/A4324_da_DK.pdf" });
        }
    }
}